name: Staging Lock Check

on:
  workflow_call:
    inputs:
      self_hosted_runner_labels:
        description: 'JSON array of runner labels. Empty = ubuntu-latest.'
        type: string
        default: ""
    secrets:
      GH_PAT:
        required: false

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-staging-lock:
    name: check-staging-lock
    if: github.event_name == 'pull_request'
    runs-on: ${{ inputs.self_hosted_runner_labels != '' && fromJSON(inputs.self_hosted_runner_labels) || 'ubuntu-latest' }}
    steps:
      - name: trivial
        run: echo "hello from single-job-with-if debug"
